title: Sozib Al Mamun
description: Personal portfolio of Sozib Al Mamun
url: "https://sozibalmamun.github.io"
markdown: kramdown
theme: minima

# Collections
collections:
  projects:
    output: true
  blog:
    output: true
    
exclude:
  - README.md
